#spring.application.name=BusinessOwners
# ===============================
# Server Config
# ===============================
server.port=9090

# ===============================
# Database Config (MySQL Workbench)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/user_table?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
#spring.datasource.password=1234
#spring.datasource.password=sneha@123
spring.datasource.password=wIaZWEpzNf1oqtF4KsOrfQ==


#spring.datasource.password=@shubangi22pachauri
#spring.datasource.password=sneha@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT Config
# ===============================
jwt.secret=MySuperSecretKey1234567890
jwt.expiration=86400000
# 1 day in milliseconds

# ===============================
# Mail Config (Hostinger SMTP)
# ===============================
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=info@vittpath.com
#spring.mail.password=@1234Asdf@
spring.mail.password=QBYx7UtEqAtZn0N1ScaMqg==
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

enable.password.encryption=true
enable.otp.encryption=true

# ===============================
# Watchlist Config
# ===============================
max.allowed.watchlist=7

# -----------------------------
# Kite Connect API Keys
# -----------------------------
kite.api.key=0g5iw80s89eu3xyy
kite.api.secret=g6pyh0n95bdc8a67p3kriurgd69fdbps
kite.user.id=WV6795
#kite.user.id=YOT541

token.expiary.time.hours=24


# Daily OTP cleanup cron expression
# Format: second minute hour day-of-month month day-of-week
# Example: 0 50 23 * * * \u2192 runs every day at 11:50 PM
cleanup.otp.cron=0 50 23 * * *


# Token expiry time in HH:mm format (24-hour clock)
# Example: 23:50 \u2192 token will expire at 23:50 AM
token.expiry.time=23:50

#file.upload-dir=${user.dir}/uploads/profile/pics/
file.max-size=512000

spring.codec.max-in-memory-size=10MB
file.upload-dir=${user.dir}/uploads/profile/pics


